[project]
name = "session_sniffer"
description = "A packet sniffer (also known as an IP grabber/puller/sniffer) specifically designed for Peer-To-Peer (P2P) video games on PC and consoles (PlayStation and Xbox)."
version = "v1.3.7 - 30/03/2025 (16:16)"

[tool.ruff]
select = ["ALL"]  # Enables all rules
ignore = []       # Ensures nothing is ignored

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true

[tool.pylint]
disable = ["line-too-long", "missing-class-docstring", "missing-function-docstring", "import-outside-toplevel"]
